permissions:
  contents: read
  pages: write
  id-token: write

name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    name: generate site and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker compose pull
        run: |
          docker run \
            -v ${PWD}/sluggy.toml:/usr/src/sluggy/sluggy.toml \
            -v ${PWD}/site:/usr/src/sluggy/site \
            -v ${PWD}/output:/usr/src/sluggy/output \
            tyronetudehope/sluggy:main \
            sluggy \
            --config /usr/src/sluggy/sluggy.toml \
            generate
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './output'
      - id: deployment
        uses: actions/deploy-pages@v2
