permissions:
  contents: read
  pages: write
  id-token: write

name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    name: generate site and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: yarn install --frozen-lockfile

      - name: compile tailwindcss
        run: yarn build

      - name: generate
        run: |
          docker run \
            -v ${PWD}/sluggy.toml:/usr/src/sluggy/sluggy.toml \
            -v ${PWD}/site:/usr/src/sluggy/site \
            -v ${PWD}/output:/usr/src/sluggy/output \
            tyronetudehope/sluggy:main \
            sluggy \
            --config /usr/src/sluggy/sluggy.toml \
            generate

      - name: copy 404
        run: |
          cp output/_error/404/index.html output/404.html

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: './output'

      - id: deployment
        uses: actions/deploy-pages@v2
